### ISSUE TITLE
Error when installing PEGASUS

### ISSUE THREAD

**Issue by komalsrathi** [Xinglab/PEGASAS#4]
Trying to install PEGASUS using python2.7 and getting this error `ImportError: No module named tools.version_utils`: 

```
(base) ➜  PEGASAS git:(master) ✗ python2.7 setup.py install
running install
running bdist_egg
running egg_info
writing requirements to PEGASAS.egg-info/requires.txt
writing PEGASAS.egg-info/PKG-INFO
writing top-level names to PEGASAS.egg-info/top_level.txt
writing dependency_links to PEGASAS.egg-info/dependency_links.txt
reading manifest file 'PEGASAS.egg-info/SOURCES.txt'
writing manifest file 'PEGASAS.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-13.4-arm64/egg
running install_lib
running build_py
creating build/bdist.macosx-13.4-arm64/egg
creating build/bdist.macosx-13.4-arm64/egg/PEGASAS
copying build/lib/PEGASAS/config.py -> build/bdist.macosx-13.4-arm64/egg/PEGASAS
copying build/lib/PEGASAS/cor_matrix_direct_perm.R -> build/bdist.macosx-13.4-arm64/egg/PEGASAS
copying build/lib/PEGASAS/PEGASAS_correlation.py -> build/bdist.macosx-13.4-arm64/egg/PEGASAS
copying build/lib/PEGASAS/PEGASAS_pathway.py -> build/bdist.macosx-13.4-arm64/egg/PEGASAS
copying build/lib/PEGASAS/GO_enrichr_plot.R -> build/bdist.macosx-13.4-arm64/egg/PEGASAS
copying build/lib/PEGASAS/__init__.py -> build/bdist.macosx-13.4-arm64/egg/PEGASAS
copying build/lib/PEGASAS/GO_plot.R -> build/bdist.macosx-13.4-arm64/egg/PEGASAS
copying build/lib/PEGASAS/prepareGeneMatrixOrdered.py -> build/bdist.macosx-13.4-arm64/egg/PEGASAS
creating build/bdist.macosx-13.4-arm64/egg/PEGASAS/data
copying build/lib/PEGASAS/data/hallmarks50.gmt.txt -> build/bdist.macosx-13.4-arm64/egg/PEGASAS/data
copying build/lib/PEGASAS/data/__init__.py -> build/bdist.macosx-13.4-arm64/egg/PEGASAS/data
copying build/lib/PEGASAS/generateMatrixbySample.py -> build/bdist.macosx-13.4-arm64/egg/PEGASAS
byte-compiling build/bdist.macosx-13.4-arm64/egg/PEGASAS/config.py to config.pyc
byte-compiling build/bdist.macosx-13.4-arm64/egg/PEGASAS/PEGASAS_correlation.py to PEGASAS_correlation.pyc
byte-compiling build/bdist.macosx-13.4-arm64/egg/PEGASAS/PEGASAS_pathway.py to PEGASAS_pathway.pyc
byte-compiling build/bdist.macosx-13.4-arm64/egg/PEGASAS/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-13.4-arm64/egg/PEGASAS/prepareGeneMatrixOrdered.py to prepareGeneMatrixOrdered.pyc
byte-compiling build/bdist.macosx-13.4-arm64/egg/PEGASAS/data/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-13.4-arm64/egg/PEGASAS/generateMatrixbySample.py to generateMatrixbySample.pyc
creating build/bdist.macosx-13.4-arm64/egg/EGG-INFO
installing scripts to build/bdist.macosx-13.4-arm64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.macosx-13.4-arm64/egg/EGG-INFO/scripts
copying build/scripts-2.7/PEGASAS -> build/bdist.macosx-13.4-arm64/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-13.4-arm64/egg/EGG-INFO/scripts/PEGASAS to 755
copying PEGASAS.egg-info/PKG-INFO -> build/bdist.macosx-13.4-arm64/egg/EGG-INFO
copying PEGASAS.egg-info/SOURCES.txt -> build/bdist.macosx-13.4-arm64/egg/EGG-INFO
copying PEGASAS.egg-info/dependency_links.txt -> build/bdist.macosx-13.4-arm64/egg/EGG-INFO
copying PEGASAS.egg-info/requires.txt -> build/bdist.macosx-13.4-arm64/egg/EGG-INFO
copying PEGASAS.egg-info/top_level.txt -> build/bdist.macosx-13.4-arm64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/PEGASAS-1.1.1-py2.7.egg' and adding 'build/bdist.macosx-13.4-arm64/egg' to it
removing 'build/bdist.macosx-13.4-arm64/egg' (and everything under it)
Processing PEGASAS-1.1.1-py2.7.egg
Removing /Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/PEGASAS-1.1.1-py2.7.egg
Copying PEGASAS-1.1.1-py2.7.egg to /Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages
PEGASAS 1.1.1 is already the active version in easy-install.pth
Installing PEGASAS script to /Users/rathik/.pyenv/versions/2.7.18/bin

Installed /Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/PEGASAS-1.1.1-py2.7.egg
Processing dependencies for PEGASAS==1.1.1
Searching for scipy
Reading https://pypi.org/simple/scipy/
Downloading https://files.pythonhosted.org/packages/a6/98/fceb84466a74b8fe74ce2dcc3a0a89cb7b4a689d4775e0fb4c95f335ef6a/scipy-1.11.1.tar.gz#sha256=fb5b492fa035334fd249f0973cc79ecad8b09c604b42a127a677b45a9a3d4289
Best match: scipy 1.11.1
Processing scipy-1.11.1.tar.gz
Writing /var/folders/hs/dhj65y752djbrytfxzz6t13h35p24r/T/easy_install-dgXaxQ/scipy-1.11.1/setup.cfg
Running scipy-1.11.1/setup.py -q bdist_egg --dist-dir /var/folders/hs/dhj65y752djbrytfxzz6t13h35p24r/T/easy_install-dgXaxQ/scipy-1.11.1/egg-dist-tmp-szTJYW
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    main()
  File "setup.py", line 29, in main
    install_requires=['matplotlib','numpy','scipy']
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/rathik/.pyenv/versions/2.7.18/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/hs/dhj65y752djbrytfxzz6t13h35p24r/T/easy_install-dgXaxQ/scipy-1.11.1/setup.py", line 27, in <module>
    'hallmarks50.gmt.txt'],'PEGASAS':[
ImportError: No module named tools.version_utils
```

Now I am trying to `tools` but getting a weird error:

```
(base) ➜  PEGASAS git:(master) ✗ pip2.7 install tools
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting tools
  Using cached tools-0.1.9.tar.gz (34 kB)
Collecting pytils
  Using cached pytils-0.4.1.tar.gz (99 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Package u'pytils' requires a different Python: 2.7.18 not in '>=3.7,<4.0'
```

Any ideas on how to resolve this?

**Comment by komalsrathi** [comment]
Resolved by changing print statements and making it compatible with python3.
